import {
  Branch,
  Module,
  Scheme,
  UploadResult,
  UploadError,
  ColumnMapping,
  ValidationRule,
} from './types'

export const mockBranches: Branch[] = [
  {
    id: '1',
    name: 'Main Branch - Mumbai',
    code: 'MUM-001',
    location: 'Mumbai, Maharashtra',
    isActive: true,
  },
  {
    id: '2',
    name: 'Delhi Branch',
    code: 'DEL-001',
    location: 'New Delhi',
    isActive: true,
  },
  {
    id: '3',
    name: 'Bangalore Branch',
    code: 'BNG-001',
    location: 'Bangalore, Karnataka',
    isActive: true,
  },
  {
    id: '4',
    name: 'Kolkata Branch',
    code: 'KOL-001',
    location: 'Kolkata, West Bengal',
    isActive: true,
  },
  {
    id: '5',
    name: 'Chennai Branch',
    code: 'CHN-001',
    location: 'Chennai, Tamil Nadu',
    isActive: false,
  },
]

export const mockModules: Module[] = [
  {
    id: '1',
    name: 'Members',
    code: 'MEM',
    description: 'Member management and records',
    isActive: true,
  },
  {
    id: '2',
    name: 'Deposits',
    code: 'DEP',
    description: 'Deposit accounts and transactions',
    isActive: true,
  },
  {
    id: '3',
    name: 'Loans',
    code: 'LAN',
    description: 'Loan accounts and disbursements',
    isActive: true,
  },
]

export const mockSchemes: Scheme[] = [
  {
    id: '1',
    moduleId: '1',
    name: 'Regular Membership',
    code: 'MEM-REG',
    description: 'Regular membership scheme',
    isActive: true,
  },
  {
    id: '2',
    moduleId: '1',
    name: 'Life Member',
    code: 'MEM-LIFE',
    description: 'Lifetime membership scheme',
    isActive: true,
  },
  {
    id: '3',
    moduleId: '2',
    name: 'Savings Account',
    code: 'DEP-SAV',
    description: 'Savings deposit scheme',
    isActive: true,
  },
  {
    id: '4',
    moduleId: '2',
    name: 'Fixed Deposit',
    code: 'DEP-FD',
    description: 'Fixed deposit scheme',
    isActive: true,
  },
  {
    id: '5',
    moduleId: '3',
    name: 'Personal Loan',
    code: 'LAN-PER',
    description: 'Personal loan scheme',
    isActive: true,
  },
  {
    id: '6',
    moduleId: '3',
    name: 'Business Loan',
    code: 'LAN-BUS',
    description: 'Business loan scheme',
    isActive: true,
  },
]

export const mockUploadHistory: UploadResult[] = [
  {
    id: 'UPL-001',
    branchId: '1',
    branchName: 'Main Branch - Mumbai',
    moduleId: '1',
    moduleName: 'Members',
    schemeId: '1',
    schemeName: 'Regular Membership',
    totalRows: 1500,
    successRows: 1485,
    failedRows: 15,
    status: 'partial',
    uploadedAt: '2024-04-25T10:30:00Z',
    fileName: 'members_data_april.xlsx',
    errorCount: 15,
  },
  {
    id: 'UPL-002',
    branchId: '2',
    branchName: 'Delhi Branch',
    moduleId: '2',
    moduleName: 'Deposits',
    schemeId: '3',
    schemeName: 'Savings Account',
    totalRows: 2300,
    successRows: 2300,
    failedRows: 0,
    status: 'success',
    uploadedAt: '2024-04-24T14:15:00Z',
    fileName: 'deposits_delhi_april.xlsx',
    errorCount: 0,
  },
  {
    id: 'UPL-003',
    branchId: '3',
    branchName: 'Bangalore Branch',
    moduleId: '3',
    moduleName: 'Loans',
    schemeId: '5',
    schemeName: 'Personal Loan',
    totalRows: 800,
    successRows: 450,
    failedRows: 350,
    status: 'failed',
    uploadedAt: '2024-04-23T09:45:00Z',
    fileName: 'loans_bangalore_april.xlsx',
    errorCount: 350,
  },
  {
    id: 'UPL-004',
    branchId: '1',
    branchName: 'Main Branch - Mumbai',
    moduleId: '1',
    moduleName: 'Members',
    schemeId: '2',
    schemeName: 'Life Member',
    totalRows: 650,
    successRows: 650,
    failedRows: 0,
    status: 'success',
    uploadedAt: '2024-04-22T16:20:00Z',
    fileName: 'life_members_april.xlsx',
    errorCount: 0,
  },
  {
    id: 'UPL-005',
    branchId: '4',
    branchName: 'Kolkata Branch',
    moduleId: '2',
    moduleName: 'Deposits',
    schemeId: '4',
    schemeName: 'Fixed Deposit',
    totalRows: 1200,
    successRows: 1150,
    failedRows: 50,
    status: 'partial',
    uploadedAt: '2024-04-21T11:00:00Z',
    fileName: 'fd_kolkata_april.xlsx',
    errorCount: 50,
  },
]

export const mockErrors: UploadError[] = [
  {
    id: 'ERR-001',
    uploadId: 'UPL-001',
    rowNumber: 45,
    columnName: 'email',
    errorMessage: 'Invalid email format',
    errorType: 'validation',
    actualValue: 'john@invalid',
  },
  {
    id: 'ERR-002',
    uploadId: 'UPL-001',
    rowNumber: 78,
    columnName: 'phone',
    errorMessage: 'Phone number must be 10 digits',
    errorType: 'format',
    actualValue: '9898989',
  },
  {
    id: 'ERR-003',
    uploadId: 'UPL-001',
    rowNumber: 123,
    columnName: 'joinDate',
    errorMessage: 'Date format should be YYYY-MM-DD',
    errorType: 'format',
    actualValue: '25-04-2024',
  },
  {
    id: 'ERR-004',
    uploadId: 'UPL-001',
    rowNumber: 156,
    columnName: 'membershipId',
    errorMessage: 'Membership ID already exists',
    errorType: 'unique',
    actualValue: 'MEM-12345',
  },
  {
    id: 'ERR-005',
    uploadId: 'UPL-001',
    rowNumber: 234,
    columnName: 'name',
    errorMessage: 'Name field is required',
    errorType: 'required',
  },
  {
    id: 'ERR-006',
    uploadId: 'UPL-003',
    rowNumber: 12,
    columnName: 'loanAmount',
    errorMessage: 'Amount must be greater than 0',
    errorType: 'validation',
    actualValue: '-50000',
  },
  {
    id: 'ERR-007',
    uploadId: 'UPL-003',
    rowNumber: 45,
    columnName: 'interestRate',
    errorMessage: 'Interest rate out of valid range (0-30%)',
    errorType: 'range',
    actualValue: '45.5',
  },
  {
    id: 'ERR-008',
    uploadId: 'UPL-005',
    rowNumber: 156,
    columnName: 'maturityDate',
    errorMessage: 'Maturity date must be after opening date',
    errorType: 'validation',
  },
]

export const mockColumnMappings: ColumnMapping[] = [
  {
    id: '1',
    schemeId: '1',
    excelColumn: 'A',
    databaseColumn: 'member_id',
    dataType: 'string',
    isRequired: true,
  },
  {
    id: '2',
    schemeId: '1',
    excelColumn: 'B',
    databaseColumn: 'name',
    dataType: 'string',
    isRequired: true,
  },
  {
    id: '3',
    schemeId: '1',
    excelColumn: 'C',
    databaseColumn: 'email',
    dataType: 'string',
    isRequired: true,
  },
  {
    id: '4',
    schemeId: '1',
    excelColumn: 'D',
    databaseColumn: 'phone',
    dataType: 'string',
    isRequired: true,
  },
  {
    id: '5',
    schemeId: '1',
    excelColumn: 'E',
    databaseColumn: 'join_date',
    dataType: 'date',
    isRequired: true,
  },
  {
    id: '6',
    schemeId: '1',
    excelColumn: 'F',
    databaseColumn: 'status',
    dataType: 'string',
    isRequired: false,
  },
]

export const mockValidationRules: ValidationRule[] = [
  {
    id: '1',
    schemeId: '1',
    columnName: 'member_id',
    ruleType: 'required',
    errorMessage: 'Member ID is required',
  },
  {
    id: '2',
    schemeId: '1',
    columnName: 'email',
    ruleType: 'email',
    errorMessage: 'Invalid email format',
  },
  {
    id: '3',
    schemeId: '1',
    columnName: 'phone',
    ruleType: 'regex',
    ruleValue: '^[0-9]{10}$',
    errorMessage: 'Phone must be exactly 10 digits',
  },
  {
    id: '4',
    schemeId: '1',
    columnName: 'member_id',
    ruleType: 'unique',
    errorMessage: 'Member ID must be unique',
  },
  {
    id: '5',
    schemeId: '3',
    columnName: 'balance',
    ruleType: 'min',
    ruleValue: 0,
    errorMessage: 'Balance must be greater than 0',
  },
  {
    id: '6',
    schemeId: '5',
    columnName: 'loan_amount',
    ruleType: 'max',
    ruleValue: 5000000,
    errorMessage: 'Loan amount cannot exceed 50 lakhs',
  },
]
