export const TEMPLATE_CONFIG = {
  membership: [
    "full_name",
    "father_name",
    "gender",
    "date_of_birth",
    "email",
    "customer_type",
    "spouse_name",
    "marital_status",
    "blood_group",
    "caste_category",
    "occupation",
    "qualification",
    "qualification_details",
    "mobile_no",
    "alt_mobile_no",
    "aadhaar_no",
    "pan_no",
    "ration_no",
    "driving_license_no",
    "house_no",
    "street",
    "village",
    "thaluk",
    "district",
    "state",
    "pincode",
    "address_email",
    "phone_no",
    "permanent_house_no",
    "permanent_street",
    "permanent_village",
    "permanent_thaluk",
    "permanent_district",
    "permanent_state",
    "permanent_pincode",
    "permanent_email",
    "permanent_phone_no",
    "membership_class",
    "member_type",
    "membership_no",
    "join_date",
    "close_date",
    "membership_status",
    "board_resolution_number",
    "ledger_folio_number",
    "board_resolution_date",
  ],

  loan: [
    "account_number",
    "customer_name",
    "loan_amount",
    "interest_rate",
    "start_date",
    "end_date",
  ],
} as const

export type ModuleKey = keyof typeof TEMPLATE_CONFIG